<div class="thrv-leads-slide-in tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content tve_empty_dropzone" data-css="tve-u-05b03d66ee29f5">
<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_tl_state_switch" data-css="tve-u-15b03d66ee2a44" data-tcb-events="|open_state_2|"><svg class="tcb-icon" viewBox="0 0 30 32" data-name="close">
<path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path>
<path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path>
</svg></div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-25b03d66ee2a86" data-float="1">
<div class="tve-content-box-background" data-css="tve-u-35b03d66ee2ac4"></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-45b03d66ee2b03"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-55b03d66ee2b42" style="">
<div class="tve-content-box-background" data-css="tve-u-65b03d66ee2b80" data-clip-id="dcg36vb47xrj6"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-tablet-top-dcg36vb47xrj6" class="decoration-clip clip-path-tablet-top" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="none" data-inverted="true" pointer-width="5" pointer-height="5" clip-path="url(#clip-tablet-bottom-dcg36vb47xrj6)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-tablet-bottom-dcg36vb47xrj6" class="decoration-clip clip-path-tablet-bottom" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="none" data-inverted="true" pointer-width="10" pointer-height="3" style=""><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-top-dcg36vb47xrj6" class="decoration-clip clip-path-mobile-top" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" data-inverted="true" pointer-width="5" pointer-height="5" clip-path="url(#clip-mobile-bottom-dcg36vb47xrj6)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-bottom-dcg36vb47xrj6" class="decoration-clip clip-path-mobile-bottom" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" data-inverted="true" pointer-width="10" pointer-height="3" style=""><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b03d66ee2bbf"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box tcb-mobile-hidden" data-css="tve-u-85b03d66ee2bfe" data-float="1">
<div class="tve-content-box-background" data-css="tve-u-95b03d66ee2c3d"></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-105b03d66ee2c7b"><div class="thrv_wrapper thrv_heading" data-tag="h2" data-css="tve-u-115b03d66ee2cc8"><h2 data-css="tve-u-125b03d66ee2d0c" style="text-align: center;"><strong>Enter a few wo​​​​rds here</strong></h2></div></div>
</div></div>
</div><div class="thrv_wrapper thrv_heading" data-tag="h2" data-css="tve-u-135b03d66ee2d4b"><h2 data-css="tve-u-145b03d66ee2d89" style="text-align: center;"><strong> 101 free tips</strong></h2></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-155b03d66ee2dc8"><p data-css="tve-u-165b03d66ee2dee" style="text-align: center;">Don't hesitate to learn all about "your subject" with our amazing guide!</p></div><div class="thrv_wrapper thrv-button tve_ea_tl_state_lightbox" data-css="tve-u-175b03d66ee2e2d" data-tcb_hover_state_parent="" data-button-style="full_rounded">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_3|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-185b03d66ee2e6b"><strong>Get your guide now</strong></span></span>
</a>
</div></div>
</div></div>