<div class="thrv_wrapper thrv-page-section" data-tve-style="1">
<div class="tve-page-section-out" data-css="tve-u-15d847b3901"></div>
<div class="tve-page-section-in tve_empty_dropzone"><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15d847b0115" style=""><span class="tve_image_frame"><img class="tve_image" alt="" width="255" height="55" title="confluence_logo" src="{tcb_lp_base_url}/css/images/confluence_logo.png" srcset="{tcb_lp_base_url}/css/images/confluence_logo-150x55-1.png 150w, {tcb_lp_base_url}/css/images/confluence_logo.png 255w" sizes="(max-width:255px) 100vw, 255px" data-id="126"></span></div></div>
</div><div class="thrv_wrapper thrv-page-section" data-tve-style="1" data-css="tve-u-15dc1713f3a">
<div class="tve-page-section-out" data-css="tve-u-15d847cbe92"></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-15d847dcff6"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-15dc170efdf"><h5 class="" data-css="tve-u-15dc1708213" style="text-align: center;">Live training webinar</h5></div><div class="thrv_wrapper thrv_heading" data-css="tve-u-15d847ee3f7"><h1 data-css="tve-u-15d8497364e" style="text-align: center;"><strong><span style="text-shadow: rgba(0, 0, 0, 0.4) 1px 1px 2px;">Marketing secrets for<br>Highly profitable online small businesses</span></strong></h1></div><div class="thrv_wrapper thrv-columns" data-css="tve-u-15dc17a0e49"><div class="tcb-flex-row tcb--cols--4 tcb-resized tcb-medium-no-wrap" data-css="tve-u-15dc1793b10"><div class="tcb-flex-col" data-css="tve-u-15dc177d3e7"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_heading" data-css="tve-u-15dc19ff733"><h3 data-css="tve-u-15dc19e9ecd" style="text-align: center;"><strong>LIVE TRAINING WEBINAR</strong></h3></div></div></div><div class="tcb-flex-col" data-css="tve-u-15dc177d40b" style="width: 282px;"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15dc175736a"><span class="tve_image_frame" style="width: 100%;"><img class="tve_image" alt="" srcset="{tcb_lp_base_url}/css/images/confluence-whammy-image1-150x150.png 150w, {tcb_lp_base_url}/css/images/confluence-whammy-image1.png 201w" sizes="(max-width:201px) 100vw, 201px" width="201" height="176" title="confluence-whammy-image1" data-id="123" src="{tcb_lp_base_url}/css/images/confluence-whammy-image1.png" style="width: 100%;"></span></div><div class="thrv_wrapper thrv_icon tcb-icon-display" data-css="tve-u-15dc177607e" data-float="1"><svg class="tcb-icon" viewBox="0 0 22 28" data-name="plus">
<title>plus</title>
<path d="M22 11.5v3c0 0.828-0.672 1.5-1.5 1.5h-6.5v6.5c0 0.828-0.672 1.5-1.5 1.5h-3c-0.828 0-1.5-0.672-1.5-1.5v-6.5h-6.5c-0.828 0-1.5-0.672-1.5-1.5v-3c0-0.828 0.672-1.5 1.5-1.5h6.5v-6.5c0-0.828 0.672-1.5 1.5-1.5h3c0.828 0 1.5 0.672 1.5 1.5v6.5h6.5c0.828 0 1.5 0.672 1.5 1.5z"></path>
</svg></div></div></div><div class="tcb-flex-col" data-css="tve-u-15dc177d450"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15dc175e489"><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-1794" alt="" width="127" height="183" title="confluence-whammy-image2 tr" data-id="1794" src="{tcb_lp_base_url}/css/images/confluence-whammy-image2-tr.png" style="width: 100%;"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-15dc177d472"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_heading" data-css="tve-u-15dc1a01d8c"><h3 data-css="tve-u-15dc19eb249"><strong>"10 TIPS FOR BETTER LANDING PAGES"</strong></h3></div></div></div></div></div></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15d84819aa7" style="">
<div class="tve-content-box-background" data-css="tve-u-15d84815955"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_heading" data-css="tve-u-15dc183108a"><h4 data-css="tve-u-15dc18105fc" style="text-align: center;"><strong>Register your spot on the webinar today <br>and you'll receive instant access to our free landing page optimization g​​​​​uide.</strong></h4></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-15dc1842f0c"><p style="text-align: center;">In the guide, you'll find simple tweaks that you can apply to boost your conversion rates immediately and it's the perfect intro to the more advanced techniques you'll learn about on the live webinar.</p></div><div class="thrv_wrapper thrv-button tve_ea_thrive_lightbox" data-css="tve-u-15d848b5652">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-css="tve-u-15d8485aca3" data-tcb-events="__TCB_EVENT_[{&quot;config&quot;:{&quot;l_anim&quot;:&quot;slide_top&quot;,&quot;l_id&quot;:&quot;4283&quot;},&quot;a&quot;:&quot;thrive_lightbox&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-15dc1a1cfec"><span style="color: rgb(51, 51, 51);"><strong><span style="font-size: 28px;"><span style="font-family: Open Sans;">CLICK HERE TO RESERVE YOUR SPOT</span></span></strong></span></span></span>
</a>
</div></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15d848acafa" style="">
<div class="tve-content-box-background" data-css="tve-u-15d848b357a"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_heading" data-css="tve-u-15d848b972c"><h2 data-css="tve-u-15dc1855ebf" style="text-align: center;"><strong>What you'll discover on this live webinar:</strong></h2></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-15d84919566"><ol class=""><li class=""><span style="font-family: &quot;Open Sans&quot;; font-size: 18px;">Sed dolor sem, consectetuer gravida, ultrices sed, tristique sit amet, dui. Suspendisse posuere ipsum vehicula urna.</span><br><span style="font-family: &quot;Open Sans&quot;; font-size: 18px;">​</span><span style="font-family: &quot;Open Sans&quot;; font-size: 18px;"></span><br></li><li class="" data-css="tve-u-15dc1545388"><span id="fr-break"></span><span style="font-size: 18px;"><span style="font-family: Open Sans;">Ut bibendum venenatis ante. Etiam eget libero. Pellentesque vel eros. Nam accumsan metus cursus purus.</span></span><br><span style="font-size: 18px;"><span style="font-family: Open Sans;">​</span></span></li><li><span style="font-family: &quot;Open Sans&quot;; font-size: 18px;">Maecenas sit amet turpis. Ut sollicitudin pede sed nunc. Ut iaculis nulla vulputate magna. Nulla enim. Integer elit.</span><br><span style="font-family: &quot;Open Sans&quot;; font-size: 18px;">​</span></li></ol></div><div class="thrv_wrapper thrv-button tve_ea_thrive_lightbox" data-css="tve-u-15d84847711">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-css="tve-u-15d8485aca3" data-tcb-events="__TCB_EVENT_[{&quot;config&quot;:{&quot;l_anim&quot;:&quot;slide_top&quot;,&quot;l_id&quot;:&quot;4283&quot;},&quot;a&quot;:&quot;thrive_lightbox&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text"><span style="color: rgb(51, 51, 51);"><strong><span style="font-size: 28px;"><span style="font-family: Open Sans;">CLICK HERE TO GAIN ACCESS</span></span></strong></span></span></span>
</a>
</div></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15dc186abe8" style="">
<div class="tve-content-box-background" data-css="tve-u-15d84815955"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv-columns" data-css="tve-u-15dc1958978"><div class="tcb-flex-row tcb--cols--2"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone"><p style="text-align: center;"><strong><span style="color: rgb(47, 110, 146);">PRESENTED BY</span></strong></p></div><div class="thrv_wrapper tve_image_caption img_style_circle" data-css="tve-u-15dc1889be6"><span class="tve_image_frame"><img class="tve_image" alt="" srcset="{tcb_lp_base_url}/css/images/shane_melaugh2-150x150.jpg 150w, {tcb_lp_base_url}/css/images/shane_melaugh2.jpg 165w" sizes="(max-width:165px) 100vw, 165px" width="165" height="165" title="shane_melaugh2" data-id="347" src="{tcb_lp_base_url}/css/images/shane_melaugh2.jpg"></span></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone"><p style="text-align: center;"><strong><span style="color: rgb(47, 110, 146);">SHANE MELAUGH</span></strong></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone"><p data-css="tve-u-15dc18da3c3" style="text-align: center;"><strong><span style="color: rgb(102, 102, 102);">Thrive Themes</span></strong></p></div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone" data-css="tve-u-15dc1a480c2"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone"><p style="text-align: center;"><strong><span style="color: rgb(47, 110, 146);">WEBINAR TIME AND DATE</span></strong></p></div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15dc1923a57">
<div class="tve-content-box-background" data-css="tve-u-15dc191f76b"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_text_element"><h3 class="" data-css="tve-u-15dc1931f59" style="text-align: center;">AUGUST 15</h3></div></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15dc1925d8c">
<div class="tve-content-box-background" data-css="tve-u-15dc18fb7d2"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone"><p data-css="tve-u-15dc193e19a" style="text-align: center;">Saturday</p><p data-css="tve-u-15dc193e19a" style="text-align: center;"><span style="color: rgb(47, 110, 146);"><strong>10 PM</strong></span></p><p data-css="tve-u-15dc193e19a" style="text-align: center;"><span style="color: rgb(47, 110, 146);"><strong>GMT</strong></span></p></div></div>
</div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone"><p style="text-align: center;"><span style="color: rgb(47, 110, 146);">TIME LEFT</span></p></div><div class="thrv_wrapper thrv_countdown_timer thrv-countdown_timer_plain tve_clearfix tve_red tve_countdown_1" data-date="2017-08-31" data-hour="11" data-min="24" data-timezone="+00:00" data-css="tve-u-15dc199c691">
<div class="sc_timer_content tve_clearfix tve_block_center" style="
font-size: 13px;
">
<div class="tve_t_day tve_t_part">
<div class="t-digits" style="min-width: 24px;"><span class="part-2">1</span><span class="part-1">3</span></div>
<div class="thrv-inline-text t-caption" data-css="tve-u-15df4bf6adf">DAYS</div>
</div>
<div class="tve_t_hour tve_t_part">
<div class="t-digits"><span class="part-2">0</span><span class="part-1">1</span></div>
<div class="thrv-inline-text t-caption" data-css="tve-u-15df4bf7f0a">HOURS</div>
</div>
<div class="tve_t_min tve_t_part">
<div class="t-digits"><span class="part-2">3</span><span class="part-1">2</span></div>
<div class="thrv-inline-text t-caption" data-css="tve-u-15df4bfadbf">MIN</div>
</div>
<div class="tve_t_sec tve_t_part">
<div class="t-digits"><span class="part-2">1</span><span class="part-1">2</span></div>
<div class="thrv-inline-text t-caption" data-css="tve-u-15df4bf9eb1">SEC</div>
</div>
<div class="tve_t_text" style="display: none;"></div>
</div>
</div></div></div></div></div><div class="thrv_wrapper thrv-button tve_ea_thrive_lightbox" data-css="tve-u-15d848b5652">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-css="tve-u-15d8485aca3" data-tcb-events="__TCB_EVENT_[{&quot;config&quot;:{&quot;l_anim&quot;:&quot;slide_top&quot;,&quot;l_id&quot;:&quot;4283&quot;},&quot;a&quot;:&quot;thrive_lightbox&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text"><span style="color: rgb(51, 51, 51);"><strong><span style="font-size: 28px;"><span style="font-family: Open Sans;">CLICK HERE TO RESERVE YOUR SPOT</span></span></strong></span></span></span>
</a>
</div></div>
</div><div class="thrv_wrapper thrv-page-section" data-tve-style="1" data-css="tve-u-15d84923b98" style="">
<div class="tve-page-section-out" data-css="tve-u-15d84924a0a"></div>
<div class="tve-page-section-in tve_empty_dropzone"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone"><p style="text-align: center;"><span style="color: rgb(255, 255, 255);">© {tcb_current_year} by Thrive Themes - </span><a href="#"><span style="color: rgb(255, 230, 13);"><u>Disclaimer</u></span></a></p></div></div>
</div>