<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" style="" data-css="tve-u-6459aeb6ea9b9f0"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-6459aeb6ea9ba61">
<div class="tve-content-box-background" data-css="tve-u-6459aeb6ea9bac2"></div>
<div class="tve-cb" data-css="tve-u-6459aeb6ea9bb1f"></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-6459aeb6ea9bb7d">
<div class="tve-content-box-background" data-css="tve-u-6459aeb6ea9bbe2"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-6459aeb6ea9bc40"><div class="tcb-flex-row tcb-resized tcb--cols--3 tcb-medium-no-wrap" data-css="tve-u-6459aeb6ea9bc9e"><div class="tcb-flex-col" data-css="tve-u-6459aeb6ea9bd02" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper thrv-divider tcb-mobile-hidden" data-style="tve_sep-1" data-thickness="1" data-color="rgb(218, 218, 218)" style="" data-css="tve-u-6459aeb6ea9bd61">
<hr class="tve_sep tve_sep-1">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-6459aeb6ea9bdc5" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style=""><p data-css="tve-u-6459aeb6ea9be23" data-default="Enter your text here..." style="text-align: center;">SED UT PERSPICIATIS UNDE OMNIS ISTE NATUS ERROR SIT VOLUPTATEM ACCUSA</p></div></div></div><div class="tcb-flex-col" data-css="tve-u-6459aeb6ea9bea2" style=""><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv-divider tcb-mobile-hidden" data-style="tve_sep-1" data-thickness="1" data-color="rgb(218, 218, 218)" style="" data-css="tve-u-6459aeb6ea9bf05">
<hr class="tve_sep tve_sep-1">
</div></div></div></div></div><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-6459aeb6ea9bf6c"><div class="tcb-flex-row tcb--cols--2 tcb-resized" data-css="tve-u-6459aeb6ea9bfcd"><div class="tcb-flex-col" data-css="tve-u-6459aeb6ea9c033" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption" data-css="tve-u-6459aeb6ea9c096" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2156" alt="" width="88" height="126" title="eight_set_postfooter_img" data-id="2156" src="{tve_leads_base_url}/images/eight_set_postfooter_img.png" style="width: 100%;"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-6459aeb6ea9c0fd" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-6459aeb6ea9c15e"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-6459aeb6ea9c1c4"><p data-css="tve-u-6459aeb6ea9c226" data-default="Enter your text here...">LEARN HOW TO MAKE A <span data-css="tve-u-6459aeb6ea9c28c" style="color: rgb(28, 129, 165);">WEBSITE WITH WORDPRESS</span></p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style=""><p data-css="tve-u-6459aeb6ea9c2ed" data-default="Enter your text here...">Lorem ipsum dolor sit amet, <span data-css="tve-u-6459aeb6ea9c34d" style="color: rgb(254, 40, 114);">consectetur adipisicing</span> elit, sed do eiusmod.</p></div><div class="thrv_wrapper thrv_lead_generation" data-connection="api" style="" data-css="tve-u-6459aeb6ea9c3ad"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--3" data-css="tve-u-6459aeb6ea9c410"><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-6459aeb6ea9c479">
<input type="text" data-field="name" name="name" placeholder="Name" data-placeholder="Name" style="">
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-6459aeb6ea9c4db">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email">
</div></div></div><div class="tcb-flex-col"><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-6459aeb6ea9c544">
<button type="submit" class="tve-froala" style="">Download</button>
</div></div></div></div></div>
</div>
</form>
</div>
</div></div></div></div></div></div>
</div></div>