<div class="thrv-leads-screen-filler tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content tve_empty_dropzone" data-css="tve-u-05b06bd17aef97">
<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-15b06bd17aefc2" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__" data-float="1" data-tcb_hover_state_parent="">
<svg class="tcb-icon" viewBox="0 0 30 32" data-name="close"><path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path><path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path></svg>
</div>
<div class="thrv_wrapper thrv-page-section" data-css="tve-u-25b06bd17af009">
<div class="tve-page-section-out" data-css="tve-u-35b06bd17af05a"></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-45b06bd17af096"><div class="tcb-clear"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box tve_evt_manager_listen tve_et_tve-viewport tve_ea_thrive_animation tve_anim_slide_bottom" data-css="tve-u-55b06bd17af115" data-float="1" data-value-type="percent" data-tcb-events="__TCB_EVENT_[{&quot;t&quot;:&quot;tve-viewport&quot;,&quot;config&quot;:{&quot;anim&quot;:&quot;slide_bottom&quot;,&quot;loop&quot;:0},&quot;a&quot;:&quot;thrive_animation&quot;}]_TNEVE_BCT__" style="">
<div class="tve-content-box-background" data-css="tve-u-65b06bd17af15d" data-clip-id="judxrukzhozu1"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b06bd17af1a2"><div class="thrv_wrapper thrv-divider" data-style="tve_sep-1" data-thickness="6" data-color="rgb(45, 105, 238)" data-css="tve-u-85b06bd17af1e7">
<hr class="tve_sep tve_sep-1">
</div></div>
</div></div><div class="tcb-clear"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-95b06bd17af22c" data-float="1" data-value-type="percent">
<div class="tve-content-box-background" data-css="tve-u-65b06bd17af15d" data-clip-id="54i2xkwtk0c1q"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b06bd17af1a2"><div class="thrv_wrapper thrv-divider" data-style="tve_sep-1" data-thickness="4" data-color="rgb(45, 105, 238)" data-css="tve-u-105b06bd17af282">
<hr class="tve_sep tve_sep-1">
</div></div>
</div></div><div class="tcb-clear"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box tve_evt_manager_listen tve_et_tve-viewport tve_ea_thrive_animation tve_anim_slide_bottom" data-css="tve-u-115b06bd17af2c6" data-float="1" data-value-type="percent" data-tcb-events="__TCB_EVENT_[{&quot;t&quot;:&quot;tve-viewport&quot;,&quot;config&quot;:{&quot;anim&quot;:&quot;slide_bottom&quot;,&quot;loop&quot;:0},&quot;a&quot;:&quot;thrive_animation&quot;}]_TNEVE_BCT__" style="">
<div class="tve-content-box-background" data-css="tve-u-65b06bd17af15d" data-clip-id="jkvo6fikdafx9"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b06bd17af1a2"><div class="thrv_wrapper thrv-divider" data-style="tve_sep-1" data-thickness="2" data-color="rgb(45, 105, 238)" data-css="tve-u-125b06bd17af31b">
<hr class="tve_sep tve_sep-1">
</div></div>
</div></div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box tve_evt_manager_listen tve_et_tve-viewport tve_ea_thrive_animation tve_anim_slide_bottom" data-css="tve-u-135b06bd17af356" data-value-type="percent" data-tcb-events="__TCB_EVENT_[{&quot;t&quot;:&quot;tve-viewport&quot;,&quot;config&quot;:{&quot;anim&quot;:&quot;slide_bottom&quot;,&quot;loop&quot;:0},&quot;a&quot;:&quot;thrive_animation&quot;}]_TNEVE_BCT__" style="">
<div class="tve-content-box-background" data-css="tve-u-65b06bd17af15d" data-clip-id="wm9qneu5gsqcl"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b06bd17af1a2"><div class="thrv_wrapper thrv-divider tcb-tablet-hidden" data-style="tve_sep-2" data-thickness="11" data-color="rgb(45, 105, 238)" data-css="tve-u-145b06bd17af39c" style="">
<hr class="tve_sep tve_sep-2">
</div></div>
</div><div class="tcb-clear"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box tve_evt_manager_listen tve_et_tve-viewport tve_ea_thrive_animation tve_anim_slide_bottom" data-css="tve-u-155b06bd17af3e0" data-float="1" data-value-type="percent" data-tcb-events="__TCB_EVENT_[{&quot;t&quot;:&quot;tve-viewport&quot;,&quot;config&quot;:{&quot;anim&quot;:&quot;slide_bottom&quot;,&quot;loop&quot;:0},&quot;a&quot;:&quot;thrive_animation&quot;}]_TNEVE_BCT__" style="">
<div class="tve-content-box-background" data-css="tve-u-65b06bd17af15d" data-clip-id="bdyc4hxz53foo"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b06bd17af1a2"><div class="thrv_wrapper thrv-divider" data-style="tve_sep-2" data-thickness="16" data-color="rgb(255, 255, 255)" data-css="tve-u-165b06bd17af42c">
<hr class="tve_sep tve_sep-2">
</div></div>
</div></div><div class="tcb-clear"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-175b06bd17af46f" data-float="1" data-value-type="percent" style="">
<div class="tve-content-box-background" data-css="tve-u-65b06bd17af15d" data-clip-id="sz3p90biqzwl5"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b06bd17af1a2"><div class="thrv_wrapper thrv-divider" data-style="tve_sep-1" data-thickness="2" data-color="rgb(255, 255, 255)" data-css="tve-u-185b06bd17af4ca">
<hr class="tve_sep tve_sep-1">
</div></div>
</div></div><div class="tcb-clear"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box tve_evt_manager_listen tve_et_tve-viewport tve_ea_thrive_animation tve_anim_slide_top" data-css="tve-u-195b06bd17af50e" data-float="1" data-value-type="percent" style="" data-tcb-events="__TCB_EVENT_[{&quot;t&quot;:&quot;tve-viewport&quot;,&quot;config&quot;:{&quot;anim&quot;:&quot;slide_top&quot;,&quot;loop&quot;:0},&quot;a&quot;:&quot;thrive_animation&quot;}]_TNEVE_BCT__">
<div class="tve-content-box-background" data-css="tve-u-65b06bd17af15d" data-clip-id="ddvqz73xj8fg7"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b06bd17af1a2"><div class="thrv_wrapper thrv-divider" data-style="tve_sep-2" data-thickness="11" data-color="rgb(255, 255, 255)" data-css="tve-u-205b06bd17af553">
<hr class="tve_sep tve_sep-2">
</div></div>
</div></div><div class="tcb-clear"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box tve_evt_manager_listen tve_et_tve-viewport tve_ea_thrive_animation tve_anim_slide_top" data-css="tve-u-215b06bd17af597" data-float="1" data-value-type="percent" style="" data-tcb-events="__TCB_EVENT_[{&quot;t&quot;:&quot;tve-viewport&quot;,&quot;config&quot;:{&quot;anim&quot;:&quot;slide_top&quot;,&quot;loop&quot;:0},&quot;a&quot;:&quot;thrive_animation&quot;}]_TNEVE_BCT__">
<div class="tve-content-box-background" data-css="tve-u-65b06bd17af15d" data-clip-id="kkm99f8c4idg0"><svg width="0" height="0" class="tve-decoration-svg"><defs></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-75b06bd17af1a2"><div class="thrv_wrapper thrv-divider" data-style="tve_sep-1" data-thickness="4" data-color="rgb(255, 255, 255)" data-css="tve-u-225b06bd17af5d5">
<hr class="tve_sep tve_sep-1">
</div></div>
</div></div><div class="thrv_wrapper thrv-columns" data-css="tve-u-235b06bd17af639"><div class="tcb-flex-row tcb-resized tcb-medium-wrap v-2 tcb--cols--2" data-css="tve-u-245b06bd17af678"><div class="tcb-flex-col c-66" data-css="tve-u-255b06bd17af6bb" style=""><div class="tcb-col tve_empty_dropzone" data-css="tve-u-265b06bd17af6fd"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-275b06bd17af740" data-value-type="percent" data-float="1">
<div class="tve-content-box-background" data-css="tve-u-285b06bd17af794" data-clip-id="3gxpla3h12o5z"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-left-3gxpla3h12o5z" class="decoration-clip clip-path-left" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="slanted" slanted-angle="4" style="" data-inverted="true" pointer-width="6" pointer-height="0"><polygon points="0.0699 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-tablet-left-3gxpla3h12o5z" class="decoration-clip clip-path-tablet-left" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="none" slanted-angle="4" style="" data-inverted="true" pointer-width="6" pointer-height="0"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-left-3gxpla3h12o5z" class="decoration-clip clip-path-mobile-left" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="none" slanted-angle="4" style="" data-inverted="true" pointer-width="6" pointer-height="0"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone" data-css="tve-u-295b06bd17af7d7"><div class="thrv_wrapper thrv_heading" data-tag="h2" data-css="tve-u-305b06bd17af81a"><h2 data-css="tve-u-315b06bd17af868" style="text-align: center;"><span data-css="tve-u-325b06bd17af8c3">Don’t miss</span>
<span data-css="tve-u-335b06bd17af909">our 101 free tips</span></h2></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-345b06bd17af94c"><p data-css="tve-u-355b06bd17af991" style="text-align: center;">Learn all the tips and tricks on "your subject" with our amazing guide&nbsp;</p></div><div class="thrv_wrapper thrv-button tve_ea_tl_state_switch" data-css="tve-u-365b06bd17af9d2" data-tcb_hover_state_parent="">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_2|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-375b06bd17afa1e">Get your free guide</span></span>
</a>
</div><div class="thrv_wrapper thrv_heading tve_ea_thrive_leads_form_close on_hover" data-tag="h2" data-css="tve-u-385b06bd17afa61"><h2 data-css="tve-u-395b06bd17afaa5" style="text-align: center;"><a class="tve_evt_manager_listen tve_et_click" data-css="tve-u-405b06bd17afae8" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;,&quot;config&quot;:{}}]_TNEVE_BCT__" href="javascript%3Avoid(0)" target="_blank"><span data-css="tve-u-415b06bd17afb24">No, thanks</span></a></h2></div></div>
</div></div></div><div class="tcb-flex-col c-33" data-css="tve-u-425b06bd17afb6c" style=""><div class="tcb-col tve_empty_dropzone" data-css="tve-u-435b06bd17afba8"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-445b06bd17afbeb" data-value-type="percent" style="">
<div class="tve-content-box-background" data-css="tve-u-455b06bd17afc2e" data-clip-id="7dfol0989iniv"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-right-7dfol0989iniv" class="decoration-clip clip-path-right" clipPathUnits="objectBoundingBox" data-screen="" decoration-type="slanted" slanted-angle="8" style="" data-inverted="true"><polygon points="0 0, 0 1, 0.8595 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-right-7dfol0989iniv" class="decoration-clip clip-path-mobile-right" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="slanted" slanted-angle="5" style="" data-inverted="true" clip-path="url(#clip-mobile-left-7dfol0989iniv)"><polygon points="0 0, 0 1, 0.9125 1, 1 0"></polygon></clipPath><clipPath id="clip-tablet-right-7dfol0989iniv" class="decoration-clip clip-path-tablet-right" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="slanted" slanted-angle="4" style="" data-inverted="true" clip-path="url(#clip-tablet-left-7dfol0989iniv)"><polygon points="0 0, 0 1, 0.9301 1, 1 0"></polygon></clipPath><clipPath id="clip-tablet-mobile-right-7dfol0989iniv" class="decoration-clip clip-path-tablet-mobile-right" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="slanted" slanted-angle="5" style="" data-inverted="true" clip-path="url(#clip-tablet-left-7dfol0989iniv)"><polygon points="0 0, 0 1, 0.9125 1, 1 0"></polygon></clipPath><clipPath id="clip-mobile-left-7dfol0989iniv" class="decoration-clip clip-path-mobile-left" clipPathUnits="objectBoundingBox" data-screen="mobile-" decoration-type="slanted" slanted-angle="5" style=""><polygon points="0 0, 0.0875 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-tablet-left-7dfol0989iniv" class="decoration-clip clip-path-tablet-left" clipPathUnits="objectBoundingBox" data-screen="tablet-" decoration-type="slanted" slanted-angle="4" style="" data-inverted="false"><polygon points="0 0, 0.0699 1, 1 1, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb" data-css="tve-u-465b06bd17afc95"></div>
</div></div></div></div></div></div>
</div>
</div>